# Generated by Django 3.1.2 on 2023-02-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_futured_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='futured_img',
            new_name='featured_image',
        ),
    ]
