# Generated by Django 3.1.2 on 2023-01-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20230131_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tittle',
            new_name='title',
        ),
    ]
