# Generated by Django 3.1.2 on 2023-02-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20230220_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('Up', 'Up Vote'), ('Down', 'Down Vote')], max_length=50),
        ),
    ]
